### ISSUE TITLE
屏蔽后，有些页面一页就只剩下一两个帖子了

### ISSUE THREAD

**Issue by Huang2326** [ltxhhz/mikuclub-optimize#1]
如题，一般用这个是为了屏蔽掉那种从各论坛搬内容来发海量帖子，但是帖子质量普遍不是很精的那种搬运工账号。
但是他们在某个分区一发基本上都能占了某个区的一两页这样，然后我屏蔽这个用户后，第一页只剩一个帖子，第二页只剩三个帖子，然后直到后面有很多帖子的页，是另一个搬运工hhhhh
想看看能不能实现屏蔽掉之后，后面页码的内容能自动在当前页面排布好 这样的功能
实在不行就自动翻页插件凑合了，也不是不能用

**Comment by ltxhhz** [comment]
可以加个自动加载下一页
